"""Agrega campo stock_actual a productos

Revision ID: 166d66c9e214
Revises: 1d23aa2b18df
Create Date: 2025-06-06 10:52:49.180669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166d66c9e214'
down_revision = '1d23aa2b18df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_actual', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('stock_actual')

    # ### end Alembic commands ###
