"""Agregar campos RG90 a FacturaCompra

Revision ID: 2a1e70649a13
Revises: d4a0a890354b
Create Date: 2025-06-20 13:31:27.432651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1e70649a13'
down_revision = 'd4a0a890354b'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('facturas_compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_comprobante', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('condicion', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('timbrado', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('iva_10', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('iva_5', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('exentas', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas_compra', schema=None) as batch_op:
        batch_op.drop_column('exentas')
        batch_op.drop_column('iva_5')
        batch_op.drop_column('iva_10')
        batch_op.drop_column('timbrado')
        batch_op.drop_column('condicion')
        batch_op.drop_column('tipo_comprobante')

    # ### end Alembic commands ###
