"""Agregar modelo FacturaCompra

Revision ID: 396074ad38a0
Revises: 491b85b41e92
Create Date: 2025-06-20 08:40:09.812773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396074ad38a0'
down_revision = '491b85b41e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facturas_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('numero_factura', sa.String(length=50), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=True),
    sa.Column('monto_total', sa.Float(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('movimiento_id', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos_caja.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    op.drop_table('facturas_compra')
    # ### end Alembic commands ###
