"""Agrega campo iva_tipo a Producto

Revision ID: 491b85b41e92
Revises: factura_format_set
Create Date: 2025-06-19 10:06:09.700999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491b85b41e92'
down_revision = 'factura_format_set'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iva_tipo', sa.String(length=2), nullable=False))

    # ### end Alembic commands ###


def upgrade():
    # Agrega la columna como nullable al principio
    op.add_column('productos', sa.Column('iva_tipo', sa.String(length=2), nullable=True))

    # Establece el valor '10' por defecto para los registros existentes
    op.execute("UPDATE productos SET iva_tipo = '10'")

    # Luego cambia la columna a NOT NULL
    op.alter_column('productos', 'iva_tipo', nullable=False)

