"""Agregar modelo Proveedor

Revision ID: d4a0a890354b
Revises: 396074ad38a0
Create Date: 2025-06-20 09:32:18.617317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a0a890354b'
down_revision = '396074ad38a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ruc', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc')
    )
    with op.batch_alter_table('facturas_compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proveedor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'proveedores', ['proveedor_id'], ['id'])
        batch_op.drop_column('proveedor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas_compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proveedor', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proveedor_id')

    op.drop_table('proveedores')
    # ### end Alembic commands ###
