"""Agrego tabla Empresa

Revision ID: d5e619c8314a
Revises: 166d66c9e214
Create Date: 2025-06-13 13:57:23.005052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e619c8314a'
down_revision = '166d66c9e214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ruc', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=150), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('timbrado_numero', sa.String(length=20), nullable=False),
    sa.Column('timbrado_vigencia_desde', sa.Date(), nullable=False),
    sa.Column('timbrado_vigencia_hasta', sa.Date(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empresa')
    # ### end Alembic commands ###
